## DataSource
spring:
  datasource:
    druid:
      #监控统计拦截的filters
      filters: stat,wall
      web-stat-filter:
        enabled: true #是否启用StatFilter默认值true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
      stat-view-servlet:
        # 是否启用statViewServlet配置
        enabled: true
        # 访问监控页面
        url-pattern: "/druid/*"
        # 禁止手动重置监控数据
        reset-enable: false
        # 设置监控页面的登陆名
        login-username: root
        # 设置监控页面的登陆密码
        login-password: root
        allow:
      #慢SQL
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 10000
          log-slow-sql: true
    dynamic:
      druid:
        #配置初始化大小/最小/最大
        initial-size: 1
        min-idle: 1
        max-active: 20
        #获取连接等待超时时间
        max-wait: 60000
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        time-between-eviction-runs-millis: 60000
        #一个连接在池中最小生存的时间
        min-evictable-idle-time-millis: 30000
        validation-query: SELECT 'x' FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
      datasource:
        master:
          username: root
          password:
          url: jdbc:mysql://127.0.0.1:3306/tongframework_dev?tinyInt1isBit=false&useUnicode=true&autoReconnect=true&useSSL=false&characterEncoding=UTF8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALxvZOkzz7O7TnrHfe5CFOO55iRHDLZGb3578rUMK4cY7ttQ/c3xzjkYIoDLi5WQEEK7teWVAxMkj8XP6OdXADMCAwEAAQ==
## Log Path
logging:
  file:
    path: logs/

## File path
file:
  path: /data/deployment/file/
dataview:
  file: /data/deployment/dataview-file/
tiny:
  file:
    path: /data/deployment/tinyFile/
    url: /tinyFile/

## Swagger
swagger:
  enable: true
  title: TFW API查看器
  description: Tong Framework Back-End
  version: 1.0
  contact:
    name: Ivan@tongtech
    url: a.b.c.d
    mail: a@b.c.d

## Framework
tfw:
  basePath: http://192.168.0.7:9999